name: Build and Deploy
# Trigger on PR merges and direct pushes to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]

env:
  # Replace these with your values
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/meme-editor

jobs:
  build-and-deploy:
    # For PRs, only run on merge, not on close. For pushes, always run
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
          platforms: linux/amd64

      # Step 5: Deploy to Coolify
      # Note: The application ID can be found in your Coolify web URL after /application/
      - name: Deploy to Coolify
        run: |
          curl -X POST \
          "${{ secrets.COOLIFY_API_URL }}/api/v1/applications/${{ secrets.COOLIFY_APP_ID }}/deploy" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d "{
            \"imageTag\": \"latest\",
            \"force\": true
          }"